fix migration and add automigrate
DJWOMS/sup pull request #38
Opened 2024-02-09 08:37 UTC by AkobArm

2024-02-09 10:53 UTC, akornilkov requested changes
Предлагаю всё же посмотреть в сторону фиче-флага на автомиграцию.
В будущем возможно будем передавать хеш миграции для наката-отката на неё, то есть автоапгрейд хед, а автооткат на версию ниже\выше при этом не обязательно последнюю

2024-02-09 10:53 UTC, akornilkov commented on src/main.py
> +run_alembic_command("upgrade head")
всё здорово, но всё же предлагаю сделать фиче-флаг на такое дело хотя бы в database_config
Что-то вроде "DB_RUN_AUTOUPGRADE" с булевым да\нет

2024-02-09 10:53 UTC, akornilkov commented on migrations/env.py
> +config.set_main_option("sqlalchemy.url", settings.database_url)
Вот это вообще красавчик что так сделал. Может мы переезжать захотим с постгресса внезапно и что,перехерачивать весь проект в поисках вот таких вендор-локов

2024-02-11 07:55 UTC, akornilkov approved these changes
НА будущее надо предусмотреть всё же запуск без ошибок или незапуск если нет миграций и папок нужных в миграционной части проекта

2024-02-11 07:57 UTC, AkobArm commented on migrations/auto_migrate.py
> +    if not os.path.exists(alembic_versions_path):
добавить?

2024-02-11 08:36 UTC, merged