Meet refactoring
DJWOMS/sup pull request #46
Opened 2024-03-01 15:22 UTC by AkobArm

2024-03-03 11:03 UTC, akornilkov requested changes
Посмотри и задай вопросы в чате

2024-03-03 11:03 UTC, akornilkov commented on src/infra/repositories/usermeet_repository.py
> +from ..models.user_meet_model import UserMeetModel
Тебе самому нравится вот такое? 
Я про импорты через .. и ...

2024-03-03 11:03 UTC, akornilkov commented on src/infra/repositories/usermeet_repository.py
> +        await self.session.commit()
Вновь вопрос про транзакции.
Может всё-таки будем управлять commit и rollback на уровне сервисов и UoW?

2024-03-21 08:50 UTC, DJWOMS approved these changes

2024-03-21 08:50 UTC, merged